import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginHorizontal: 15,
		marginTop: 40,
	},
	headerText: {
		fontSize: 22,
		color: "black",
		fontFamily: "Nunito_700Bold",
		width: "60%",
	},
	headerImage: {
		height: 30,
		width: 30,
		borderRadius: 15,
	},
	searchContainer: {
		marginTop: 15,
		marginHorizontal: 15,
		borderColor: "#FBF9F7",
		borderWidth: 1,
		padding: 10,
		borderRadius: 25,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	searchInputContainer: {
		flexDirection: "row",
		alignItems: "center",
	},
	searchInput: {
		marginLeft: 10,
		fontFamily: "Nunito_600SemiBold",
		width: "75%",
		color: "black",
	},
	categoriesHeader: {
		fontSize: 22,
		fontFamily: "Nunito_700Bold",
		color: "black",
		marginHorizontal: 15,
	},
	categoriesContainer: {
		marginLeft: 12,
		padding: 10,
		marginRight: 5,
		backgroundColor: "#FBF9F7",
		borderRadius: 20,
		flexDirection: "row",
		alignItems: "center",
		marginTop: 10,
	},
	categoriesImage: {
		width: 20,
		height: 20,
		borderRadius: 15,
		marginRight: 5,
	},
	categoriesText: {
		fontSize: 15,
		fontFamily: "Nunito_600SemiBold",
	},
	locationContainer: {
		marginLeft: 15,
		marginRight: 10,
	},
	locationImage: {
		width: 300,
		height: 400,
		borderRadius: 40,
	},
	locationStars: {
		position: "absolute",
		zIndex: 1,
		top: 0,
		left: 0,
		margin: 25,
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#FBF9F7",
		padding: 10,
		borderRadius: 20,
		opacity: 0.8,
	},
	locationFavourite: {
		position: "absolute",
		zIndex: 1,
		top: 0,
		right: 0,
		margin: 25,
		backgroundColor: "#FBF9F7",
		padding: 10,
		borderRadius: 20,
		opacity: 0.8,
	},
	locationAddress: {
		position: "absolute",
		zIndex: 1,
		bottom: 20,
		margin: 25,
		backgroundColor: "#FBF9F7",
		padding: 10,
		borderRadius: 20,
		opacity: 0.8,
		alignSelf: "center",
		flexDirection: "row",
		alignItems: "center",
	},
});
